#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    :
}

reload_service() {
    /usr/bin/podkop-sub-cron-sync >/dev/null 2>&1 || \
        logger -t podkop-subscriptions "cron synchronization failed after podkop_subscriptions commit"
}

service_triggers() {
    procd_add_config_trigger "config.change" "podkop_subscriptions" /etc/init.d/podkop_subscriptions reload
}
